task: "rec"
model_name: "BookingLSTM"
seed: 71
device: cuda

fold_params:
  shuffle: True
  n_splits: 5
  random_state: 71

window_size: 20

train_loader_params:
  batch_size: 128
  shuffle: true
  num_workers: 0
  pin_memory: true

val_loader_params:
  batch_size: 128
  shuffle: false
  num_workers: 2
  pin_memory: true

test_loader_params:
  batch_size: 1
  shuffle: false
  num_workers: 2
  pin_memory: true

n_epochs: 2

encoder_params:
  embedding_size: 64
  hidden_size: 256
  layer_norm_eps: 1.0e-12
  hidden_dropout_prob: 0.1
  pad_token_id: 0
  max_elapsed_seconds: 1800

optimizer_params:
  lr: 3.0e-4
  betas:
    - 0.9
    - 0.99
  eps: 1.0e-8

file_path:
  input_dir: "/work/sigir-ecom-2021/data/input/"
  output_dir: "/work/sigir-ecom-2021/data/output/"
  feature_dir: "/work/sigir-ecom-2021/data/features/"
  interim_dir: "/work/sigir-ecom-2021/data/interim/"

raw_file:
  browsing_train: "browsing_train.csv"
  search_train: "search_train.csv"
  sku_to_content: "sku_to_content.csv"
  test: "rec_test_phase_1.json"

pkl_file:
  browsing_train: "browsing_train.pkl"
  search_train: "search_train.pkl"
  sku_to_content: "sku_to_content.pkl"
  test: "rec_test_phase_1.pkl"
  train_preprocessed: "train_preprocessed.pkl"
  test_preprocessed: "test_preprocessed.pkl"

out_file:
  test: "rec_test_phase_1_pred.json"
