task: "rec"
description: ModelNN
model_name: "BookingLSTM"
seed: 71
fold:
  shuffle: False
  n_splits: 5
params:
  num_epochs: 15
  bacth_size: 32
  emb_dim: 512
  rnn_dim: 512
  dropout: 0.3
  rnn_dropout: 0.3
file_path:
  input_dir: "/work/sigir-ecom-2021/data/input/"
  output_dir: "/work/sigir-ecom-2021/data/output/"
  feature_dir: "/work/sigir-ecom-2021/data/features/"
  interim_dir: "/work/sigir-ecom-2021/data/interim/"
raw_file:
  browsing_train: "browsing_train.csv"
  search_train: "search_train.csv"
  sku_to_content: "sku_to_content.csv"
  test: "rec_test_phase_1.json"
pkl_file:
  browsing_train: "browsing_train.pkl"
  search_train: "search_train.pkl"
  sku_to_content: "sku_to_content.pkl"
  test: "rec_test_phase_1.pkl"
  train_preprocessed: "train_preprocessed.pkl"
  test_preprocessed: "test_preprocessed.pkl"
